astar_planner:
  ros__parameters:
    # Odometry
    # spawn_x: 0.5
    # spawn_y: 0.5
    map_pub_topic_: ""
    path_pub_topic_: ""
    goal_sub_topic_: ""
    odometry_sub_topic_: ""
    robot_radius: 0.2
    safety_margin: 0.1
