controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # Define the controllers and their types here
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    left_wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    right_wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

left_wheel_velocity_controller:
  ros__parameters:
    joints:
      - left_wheel_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity
      - position

right_wheel_velocity_controller:
  ros__parameters:
    joints:
      - right_wheel_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity
      - position
